### PR TITLE
feat(appdistribution): firebaseappdistribution:v1

### PR DESCRIPTION
**Pull request by Danaru87**
Firebase AppDistribution API v1 is available.

### CODE REVIEW

**Comment by Salakar** [comment]
Thanks for this! Is it possible to keep `firebaseappdistribution:v1alpha` also, otherwise this would be a breaking change for anyone currently consuming `v1alpha`

**Comment by Salakar** [comment]
I will push a separate PR for this shortly that preserves the alpha and adds other missing versions

Edit: #3

**Comment by Danaru87** [comment]
@Salakar 
Your lib is very usefull, thanks for you work :)

**Comment by Salakar** [comment]
> @Salakar Your lib is very usefull, thanks for you work :)

Thanks! :)

v0.1.2 now has this version in

**Pull request closed without merging**
